# Generated by Django 5.1.4 on 2025-01-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
