# Generated by Django 4.2.7 on 2025-01-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='played_at',
            field=models.DateTimeField(null=True),
        ),
    ]
