name: deploy pr preview frontend

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write # needed for commenting preview url

jobs:
  preview:
    runs-on: ubuntu-latest
    environment:
      name: preview-${{ github.event.number }}
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      NEXT_PUBLIC_API_URL: https://cache-pr-${{ github.event.number }}.onrender.com
      NEXT_PUBLIC_BASE_PATH: /cache/pr-preview/${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      
      - uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      
      - uses: actions/cache@v4
        with:
          path: frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-${{ hashFiles('frontend/src/**.[jt]s', 'frontend/src/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-
      
      - name: install & build
        working-directory: frontend
        run: |
          npm ci
          npm run build
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/out
          name: pr-preview-${{ github.event.number }}
      
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: pr-preview-${{ github.event.number }}
          preview: true
      
      - uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.deployment.outputs.page_url }}';
            const fullPreviewUrl = `${previewUrl}/cache/pr-preview/${{ github.event.number }}`;
            const apiUrl = '${{ env.NEXT_PUBLIC_API_URL }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment is ready!\n\nFrontend URLs:\n- Base: ${previewUrl}\n- Full path: ${fullPreviewUrl}\nAPI URL: ${apiUrl}`
            }) 